language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  - docker build -t build:latest ./docker/build-env/

install:
  - docker build -t helloworldimg:latest .

script:
- |
  docker run --rm --name hellocont -v "$(pwd)":/home/dev/ \
  helloworldimg:latest  /bin/bash -c  \
  'cd /home/dev/build/debug && \
  rm -rf * && \
  rm -rf /home/dev/external/gtest/src/googletest-build/* && \
  cmake ../.. && \
  make googletest && \
  make HelloWorld && \
  make runDummyTest && \
  ./runDummyTest'