language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  - pip install --user cpp-coveralls
  - docker build -t build:latest ./docker/build-env/

install:
  - docker build -t helloworldimg:latest .

script:
- |
  docker run --name hellocont -v "$(pwd)":/home/dev/ \
  helloworldimg:latest  /bin/bash -c  \
  'cd /home/dev/build/debug && \
  rm -rf * && \
  rm -rf /home/dev/external/gtest/src/ && \
  rm -rf /home/dev/external/gtest/tmp/ && \
  cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ../.. && \
  make googletest && \
  make HelloWorld && \
  make runDummyTest && \
  ./runDummyTest'

after_success:
  - pwd
  - ls
  - coveralls --verbose --root . 