language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  - docker build -t build:latest ./docker/build-env/

install:
  - docker build -t helloworldimg:latest .

script:
  - docker run hellworldimg:latest /home/dev/src/build/HelloWorld