language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

    # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90

  - pip install --user cpp-coveralls
  - docker build -t build:latest ./docker/build-env/
  - gcc --version
  

install:
  - docker build -t helloworldimg:latest .

script:
  - gcov --version
- |
  docker run --name hellocont -v "$(pwd)":/home/dev/ \
  helloworldimg:latest  /bin/bash -c  \
  'cd /home/dev/build/debug && \
  rm -rf * && \
  rm -rf /home/dev/external/gtest/src/ && \
  rm -rf /home/dev/external/gtest/tmp/ && \
  cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ../.. && \
  make googletest && \
  make HelloWorld && \
  make runDummyTest && \
  ./runDummyTest'

after_success:
  - pwd
  - coveralls --verbose --root . 