language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  - docker build -t build:latest ./docker/build-env/

install:
  - docker build -t helloworldimg:latest .

script:
- |
  docker run --name hellocont -v "$(pwd)":/home/dev/ \
  helloworldimg:latest \
  'cd ./build/debug && cmake ../.. && make HelloWorld && make runDummyTest && ./runDummyTest'