language: cpp

sudo: required

services:
  - docker

compiler: gcc

before_install:
  - docker build -t build:latest -f docker/build/Dockerfile

install:
  - docker build -t helloworldimg:latest -f docker/main/Dockerfile

script:
  - docker run hellwWorldimg:latest /home/dev/src/build/HelloWorld